//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlyCoffeeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string IDTHUCUONG { get; set; }
        public string IDHOADON { get; set; }
        public Nullable<int> SOLUONGMUA { get; set; }
        public Nullable<decimal> THANHTIENMUA { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual THUCUONG THUCUONG { get; set; }
    }
}
