//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlyCoffeeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADONNHAP
    {
        public string IDHOADONNHAP { get; set; }
        public string IDNGUYENLIEU { get; set; }
        public Nullable<double> SOLUONGNHAP { get; set; }
        public Nullable<decimal> THANHTIENNHAP { get; set; }
    
        public virtual HOADONNHAP HOADONNHAP { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
