//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlyCoffeeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTHUC
    {
        public string IDNGUYENLIEU { get; set; }
        public string IDTHUCUONG { get; set; }
        public Nullable<double> SOLUONGDUNG { get; set; }
    
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual THUCUONG THUCUONG { get; set; }
    }
}
